apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: analyzer
  template:
    metadata:
      labels:
        app: analyzer
    spec:
      containers:
        - name: analyzer
          image: eduardotakemura/real-state-analyzer:latest
          imagePullPolicy: Always
          env:
            - name: API_URL
              value: "http://api:8000"
            - name: RABBITMQ_HOST
              value: "rabbitmq"
            - name: RABBITMQ_PORT
              value: "5672"
            - name: RABBITMQ_USER
              value: "guest"
            - name: RABBITMQ_PASS
              value: "guest"
