version: '3.8'
services:
  ## POSTGRESQL
  database:
    image: postgres:latest
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: properties
    volumes:
      - postgres_data:/var/lib/postgresql/data # Named volume
      - ./properties.sql:/docker-entrypoint-initdb.d/properties.sql
  ## FASTAPI BACKEND
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: properties
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app # Bind mount to live updates
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database
      - rabbitmq
  ## REACT FRONTEND
  # react:
  #   container_name: react
  #   build:
  #     context: ./react
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./react/src:/app/src # Mount only the src directory
  #     - ./react/public:/app/public # Mount only the public directory
  #     - /app/node_modules # Ignore node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true # Add this for webpack polling
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - api
  ## RABBITMQ
  rabbitmq:
    image: 'rabbitmq:management' # RabbitMQ with management plugin (UI for monitoring)
    container_name: rabbitmq
    ports:
      - '15672:15672' # RabbitMQ management UI (access via http://localhost:15672)
      - '5672:5672' # RabbitMQ AMQP protocol port (used by services to send/receive messages)
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
  ## PRICE PREDICTION MODEL
  price_model:
    build:
      context: ./price_model
      dockerfile: Dockerfile
    container_name: price_model
    volumes:
      - price_model_data:/app/data # Named volume to store data
      - ./price_model/data:/app/data # Bind mount to access models
    depends_on:
      - rabbitmq
  ## ANALYZER
  analyzer:
    build:
      context: ./analyzer
      dockerfile: Dockerfile
    container_name: analyzer
    # volumes:
    #   - ./analyzer:/app
    #restart: always
    depends_on:
      - rabbitmq
volumes:
  postgres_data:
