version: '3.8'
services:
  ## POSTGRESQL
  database:
    image: postgres:latest
    container_name: database
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: properties
    volumes:
      - postgres_data:/var/lib/postgresql/data # Named volume
      - ./properties.sql:/docker-entrypoint-initdb.d/properties.sql
  ## FASTAPI BACKEND
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: properties
    ports:
      - '8000:8000'
    volumes:
      - ./api:/app # Bind mount to live updates
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - database
  ## REACT FRONTEND
  # react:
  #   container_name: react
  #   build:
  #     context: ./react
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - '3000:3000'
  #   volumes:
  #     - ./react/src:/app/src # Mount only the src directory
  #     - ./react/public:/app/public # Mount only the public directory
  #     - /app/node_modules # Ignore node_modules
  #   environment:
  #     - CHOKIDAR_USEPOLLING=true
  #     - WATCHPACK_POLLING=true # Add this for webpack polling
  #   stdin_open: true
  #   tty: true
  #   depends_on:
  #     - api
volumes:
  postgres_data:
