apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: eduardotakemura/real-state-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: database
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: postgres
            - name: DB_NAME
              value: properties
          command: ["/bin/sh", "-c"]
          args:
            - |
              python create_tables.py &&
              uvicorn main:app --host 0.0.0.0 --port 8000 --reload
