from api.extensions import db

class Properties(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    page_id = db.Column(db.Integer, nullable=False)
    scrapping_date = db.Column(db.String, nullable=False)
    link = db.Column(db.String, nullable=False)
    title = db.Column(db.String(255), nullable=False)
    operation = db.Column(db.String(50), nullable=False)
    address = db.Column(db.String(255), nullable=False)
    size = db.Column(db.Integer, nullable=False)
    dorms = db.Column(db.Integer, nullable=False)
    toilets = db.Column(db.Integer, nullable=False)
    garage = db.Column(db.Integer, nullable=False)
    price = db.Column(db.Integer, nullable=False)
    additional_costs = db.Column(db.Integer, nullable=False)
    features = db.Column(db.Text, nullable=True)
    type = db.Column(db.String(50), nullable=False)
    street = db.Column(db.String(255), nullable=False)
    neighborhood = db.Column(db.String(255), nullable=False)
    city = db.Column(db.String(255), nullable=False)
    state = db.Column(db.String(2), nullable=False)
    latitude = db.Column(db.Float, nullable=False)
    longitude = db.Column(db.Float, nullable=False)
